import type { MetadataRoute } from "next";

// Minimal PWA manifest so Lunchball can be added to a phone's home screen.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Lunchball — Golf Money Games",
    short_name: "Lunchball",
    description: "Track scores, pops, and golf money games live on the course.",
    start_url: "/",
    display: "standalone",
    background_color: "#0C0C0E",
    theme_color: "#0C0C0E",
    icons: [
      // Lunchball bitten-ball mark — matches the header. Generated by
      // scripts/gen-icons.mjs.
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
    ],
  };
}
