import type { MetadataRoute } from "next";

// Minimal PWA manifest so Wolf can be added to a phone's home screen.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Wolf — Golf Money Game",
    short_name: "Wolf",
    description: "Track scores, pops, and the Wolf money game live on the course.",
    start_url: "/",
    display: "standalone",
    background_color: "#0C0C0E",
    theme_color: "#0C0C0E",
    icons: [
      // Wolf mark (eyes + snout) — matches the header. Generated by
      // scripts/gen-icons.mjs.
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
    ],
  };
}
